// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCqdafE7oOwnQNnwlDb98zz71KD5Znao2k',
    appId: '1:734316633860:web:885f58bd91cc16ceb9ba51',
    messagingSenderId: '734316633860',
    projectId: 'geolocation-345f3',
    authDomain: 'geolocation-345f3.firebaseapp.com',
    storageBucket: 'geolocation-345f3.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA4aNOu1ohfpnAwN2V-wNs0XOzfFweKcCk',
    appId: '1:734316633860:android:512ac43803e51668b9ba51',
    messagingSenderId: '734316633860',
    projectId: 'geolocation-345f3',
    storageBucket: 'geolocation-345f3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDpCq-q0PNr-9zZzpGDjNEdzcFFy5PRy0k',
    appId: '1:734316633860:ios:0102887197940155b9ba51',
    messagingSenderId: '734316633860',
    projectId: 'geolocation-345f3',
    storageBucket: 'geolocation-345f3.appspot.com',
    iosBundleId: 'com.example.application2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDpCq-q0PNr-9zZzpGDjNEdzcFFy5PRy0k',
    appId: '1:734316633860:ios:0102887197940155b9ba51',
    messagingSenderId: '734316633860',
    projectId: 'geolocation-345f3',
    storageBucket: 'geolocation-345f3.appspot.com',
    iosBundleId: 'com.example.application2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCqdafE7oOwnQNnwlDb98zz71KD5Znao2k',
    appId: '1:734316633860:web:7b7fc272f3bfd184b9ba51',
    messagingSenderId: '734316633860',
    projectId: 'geolocation-345f3',
    authDomain: 'geolocation-345f3.firebaseapp.com',
    storageBucket: 'geolocation-345f3.appspot.com',
  );
}
